### ISSUE TITLE
Contributing and README.md file

### ISSUE THREAD

**Issue by chaitanyakatore** [SwloBr/SortMethods#10]
- Hacktoberfest have rule for including contributing and README.md file 
- please include this otherwise it will excluded from hacktoberfest

**Comment by Joao-Victor-RVG** [comment]
Hello! We are very happy that you intend to contribute to our repository.

But we think you have more skills than just adding two topics in README file, our README file is ok and doesn't need any changes.

If you want to contribute with our code, just follow the steps in the repository and request a PR
